import { Router, Request, Response } from 'express';
import { z } from 'zod';
import { supabase } from '../lib/supabase';
import { ApiError } from '../middleware/errorHandler';

const router = Router();

// GET /orders - List orders with filters
router.get('/', async (req: Request, res: Response) => {
  const { status, customer_id, from_date, to_date, limit = '50' } = req.query;
  
  let query = supabase
    .from('orders')
    .select(`
      *,
      customer:customers(id, name)
    `)
    .order('order_date', { ascending: false })
    .order('created_at', { ascending: false })
    .limit(parseInt(limit as string, 10));
  
  if (status) {
    query = query.eq('status', status);
  }
  
  if (customer_id) {
    query = query.eq('customer_id', customer_id);
  }
  
  if (from_date) {
    query = query.gte('order_date', from_date);
  }
  
  if (to_date) {
    query = query.lte('order_date', to_date);
  }
  
  const { data, error } = await query;
  
  if (error) {
    throw new ApiError(500, error.message, 'DATABASE_ERROR');
  }
  
  res.json({ success: true, data });
});

// GET /orders/:id - Get order with items
router.get('/:id', async (req: Request, res: Response) => {
  const { id } = req.params;
  
  const { data, error } = await supabase
    .from('orders')
    .select(`
      *,
      customer:customers(*),
      items:order_items(
        *,
        product:products(id, name, type)
      )
    `)
    .eq('id', id)
    .single();
  
  if (error) {
    if (error.code === 'PGRST116') {
      throw new ApiError(404, 'Order not found', 'NOT_FOUND');
    }
    throw new ApiError(500, error.message, 'DATABASE_ERROR');
  }
  
  res.json({ success: true, data });
});

// POST /orders - Create order
const createOrderSchema = z.object({
  customer_id: z.string().uuid(),
  order_date: z.string().optional(),
  notes: z.string().optional(),
  status: z.enum(['draft', 'confirmed', 'completed', 'cancelled']).default('draft'),
});

router.post('/', async (req: Request, res: Response) => {
  const body = createOrderSchema.parse(req.body);
  
  // Order number is auto-generated by database trigger
  const { data, error } = await supabase
    .from('orders')
    .insert(body)
    .select(`
      *,
      customer:customers(id, name)
    `)
    .single();
  
  if (error) {
    throw new ApiError(500, error.message, 'DATABASE_ERROR');
  }
  
  res.status(201).json({ success: true, data });
});

// PUT /orders/:id - Update order
const updateOrderSchema = z.object({
  notes: z.string().optional(),
  status: z.enum(['draft', 'confirmed', 'completed', 'cancelled']).optional(),
  total_trays: z.number().int().min(0).optional(),
  total_tubs: z.number().int().min(0).optional(),
  total_boxes: z.number().int().min(0).optional(),
  total_weight_kg: z.number().min(0).optional(),
});

router.put('/:id', async (req: Request, res: Response) => {
  const { id } = req.params;
  const body = updateOrderSchema.parse(req.body);
  
  const { data, error } = await supabase
    .from('orders')
    .update(body)
    .eq('id', id)
    .select()
    .single();
  
  if (error) {
    throw new ApiError(500, error.message, 'DATABASE_ERROR');
  }
  
  res.json({ success: true, data });
});

// DELETE /orders/:id - Delete order (only if draft)
router.delete('/:id', async (req: Request, res: Response) => {
  const { id } = req.params;
  
  // Check if order is draft
  const { data: order } = await supabase
    .from('orders')
    .select('status')
    .eq('id', id)
    .single();
  
  if (order && order.status !== 'draft') {
    throw new ApiError(400, 'Only draft orders can be deleted', 'INVALID_STATUS');
  }
  
  const { error } = await supabase
    .from('orders')
    .delete()
    .eq('id', id);
  
  if (error) {
    throw new ApiError(500, error.message, 'DATABASE_ERROR');
  }
  
  res.json({ success: true, message: 'Order deleted' });
});

export default router;

